name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: africa-usa-trade-intelligence
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |
          docker build -t gcr.io/${PROJECT_ID}/${SERVICE_NAME}:${{ github.sha }} .
          docker push gcr.io/${PROJECT_ID}/${SERVICE_NAME}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${SERVICE_NAME} \
            --image gcr.io/${PROJECT_ID}/${SERVICE_NAME}:${{ github.sha }} \
            --platform managed \
            --region ${REGION} \
            --allow-unauthenticated \
            --port 8000 \
            --set-env-vars PORT=8000

      - name: Show Output
        run: echo "Successfully deployed to Cloud Run: ${{ steps.deploy.outputs.url }}"