name: Data Ingestion Pipeline
on:
  workflow_dispatch:
  schedule:
    # Staggered schedules to respect API rate limits
    - cron: "5 2 * * *"     # Census data at 2:05 AM UTC
    - cron: "12 2 * * *"    # FRED data at 2:12 AM UTC
    - cron: "20 2 * * *"    # FX rates at 2:20 AM UTC
    - cron: "30 2 * * *"    # World Bank + Arbitrage at 2:30 AM UTC
concurrency:
  group: data-ingestion-${{ github.event.schedule }}
  cancel-in-progress: false
jobs:
  ingest-data:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: "3.10"
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -e .
      - name: Run Census data ingestion
        run: |
          ingest-census
        if: github.event.schedule == '5 2 * * *' || github.event_name == 'workflow_dispatch'
      - name: Run FRED data ingestion
        run: |
          ingest-fred
        if: github.event.schedule == '12 2 * * *' || github.event_name == 'workflow_dispatch'
      - name: Run FX rates ingestion
        run: |
          fx-rates
        if: github.event.schedule == '20 2 * * *' || github.event_name == 'workflow_dispatch'
      - name: Run World Bank data ingestion
        run: |
          ingest-wb
        if: github.event.schedule == '30 2 * * *' || github.event_name == 'workflow_dispatch'
      - name: Calculate arbitrage opportunities
        run: |
          refresh-arbitrage
        if: github.event.schedule == '30 2 * * *' || github.event_name == 'workflow_dispatch'