name: Docker Build and Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for API
        id: meta_api
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/africa-usa-trade-intelligence-api
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
            type=ref,event=tag

      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}

      - name: Extract metadata (tags, labels) for Dashboard
        id: meta_dash
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/africa-usa-trade-intelligence-dashboard
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
            type=ref,event=tag

      - name: Build and push Dashboard image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.dashboard
          push: true
          tags: ${{ steps.meta_dash.outputs.tags }}
          labels: ${{ steps.meta_dash.outputs.labels }}

