name: Enhanced Features Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-enhanced-features:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt

    - name: Test African Market Intelligence
      run: |
        # Start the API server in the background
        python -m uvicorn src.api.main:app --host 0.0.0.0 --port 8000 &
        sleep 10
        
        # Test African markets endpoint
        curl -f http://localhost:8000/african-markets || exit 1
        
        # Test custom report endpoint
        curl -f "http://localhost:8000/custom-report?client_name=TestClient&product_focus=coffee" || exit 1

    - name: Test Data Collection Enhancements
      run: |
        python -c "
from src.data.collector import DataCollector
collector = DataCollector()

# Test African exchange data
african_data = collector.get_african_exchange_data()
print('African exchange data collected successfully')

# Test social sentiment
sentiment_data = collector.get_social_sentiment(['coffee', 'cocoa'])
print('Social sentiment data collected successfully')
"

  deploy-enhanced-dashboard:
    needs: test-enhanced-features
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Deploy Enhanced Dashboard
      run: |
        echo "# Enhanced Dashboard Deployment" > enhanced_dashboard_deployment.md
        echo "Deployment time: $(date)" >> enhanced_dashboard_deployment.md
        echo "Status: Success" >> enhanced_dashboard_deployment.md
        
        # Commit the deployment log
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add enhanced_dashboard_deployment.md
        git commit -m "Enhanced dashboard deployment log" || echo "No changes to commit"
        git push